name: 'Send update to API'
description: 'Send the event details and optionally a file from the repo to an API'
inputs:
  filepath:
    description: 'The filepath relative to the root.'
    required: true
  url:
    description: 'The API url to which the POST-request is being sent.'
    required: true

outputs:
  response: # id of output
    description: 'The server request response from the API'

runs:
  using: 'docker'
  image: 'Dockerfile'