name: 'Send update to API'
description: 'Send an repo update to an API'
inputs:
  filepath_changelog:
    description: 'The filepath to CHANGELOG.md (or alternative file that is used to track updates) relative to the root.'
    required: true
  url:
    description: 'The API url to which the POST-request is being sent.'
    required: true

outputs:
  response: # id of output
    description: 'The server request response from the API'

runs:
  using: 'docker'
  image: 'Dockerfile'